# Generated by Django 4.1.7 on 2023-03-22 18:49

from django.db import migrations, models
import studapi.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('year_joined', models.IntegerField(validators=[studapi.validators.validate_year])),
                ('date_of_birth', models.DateField()),
                ('faculty', models.CharField(max_length=70)),
                ('country', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
